"""Multimodal-cue verbal-attitude reconciliation (Eq. 1, Section 4.1.4).

The surface attitude category the model generates can contradict the
polarity-intensity signal under the divergence patterns of the expression-gap
table.  Eq. 1 resolves the contradiction by letting the polarity-intensity
signal override the surface category when the divergence is large.

Four branches fire. Each is numbered here so that the confidence score, the
review queue and the intervention counts can all name the branch that produced
them:

===  ================================================  =========================
Br.  Condition                                          Effect
===  ================================================  =========================
1    category in {L, E}, polarity neg, r <= -tau_rev    -> Dislike
2    category in {L, E}, polarity neg,                  -> Live with
     -tau_rev < r <= -tau_flag
3    category N, polarity neg, r <= -tau_flag           -> Live with
4    category D, polarity in {pos, neu}, r >= tau_flag  -> Essential
===  ================================================  =========================

No branch assigns Neutral, and that is deliberate.  Every correction the rule
makes moves a label away from the neutral midpoint; the politeness pattern is
the opposite case, and an instance whose cues are genuinely flat is
indistinguishable, on the evidence this rule consumes, from one whose cues are
weakly valenced.  Politeness is handled upstream by the adapter injection, and
the rule's only role there is to leave a correctly neutral prediction alone.
"""

from dataclasses import dataclass
from typing import Optional, Sequence

from msa_arc.config import MCVAConfig

#: Branch 0 is the "otherwise" fall-through: the surface category stands.
NO_RECONCILIATION = 0


@dataclass(frozen=True)
class Reconciliation:
    """Outcome of applying Eq. 1 to one instance.

    Attributes:
        category: The reconciled attitude category.
        branch: Which branch fired; ``NO_RECONCILIATION`` if none did.
        changed: Whether the category differs from the surface prediction.
        surface_category: The category the model generated, kept for audit.
    """

    category: str
    branch: int
    changed: bool
    surface_category: str


def reconcile(
    surface_category: str,
    polarity: str,
    intensity: float,
    cfg: Optional[MCVAConfig] = None,
) -> Reconciliation:
    """Apply Eq. 1 to a single instance.

    Args:
        surface_category: Attitude category generated by the model.
        polarity: Generated polarity, one of ``positive``/``negative``/``neutral``.
        intensity: Generated intensity on ``[-1, 1]``.
        cfg: Threshold configuration; defaults to the paper's
            ``tau_rev = 0.7``, ``tau_flag = 0.3``.

    Returns:
        A :class:`Reconciliation`. When ``cfg.enabled`` is ``False`` the surface
        category is returned untouched, which is the "without MCVA" ablation.
    """
    cfg = cfg or MCVAConfig()
    if not cfg.enabled:
        return Reconciliation(surface_category, NO_RECONCILIATION, False, surface_category)

    tau_rev, tau_flag = cfg.tau_rev, cfg.tau_flag
    negative = polarity == "negative"
    non_negative = polarity in {"positive", "neutral"}

    branch = NO_RECONCILIATION
    category = surface_category

    if surface_category in {"Like", "Essential"} and negative:
        if intensity <= -tau_rev:
            branch, category = 1, "Dislike"
        elif intensity <= -tau_flag:
            branch, category = 2, "Live with"
    elif surface_category == "Neutral" and negative and intensity <= -tau_flag:
        branch, category = 3, "Live with"
    elif surface_category == "Dislike" and non_negative and intensity >= tau_flag:
        branch, category = 4, "Essential"

    return Reconciliation(
        category=category,
        branch=branch,
        changed=category != surface_category,
        surface_category=surface_category,
    )


def reconcile_batch(
    surface_categories: Sequence[str],
    polarities: Sequence[str],
    intensities: Sequence[float],
    cfg: Optional[MCVAConfig] = None,
) -> list[Reconciliation]:
    """Apply Eq. 1 across a batch of instances.

    Args:
        surface_categories: Generated attitude categories.
        polarities: Generated polarities.
        intensities: Generated intensities.
        cfg: Threshold configuration.

    Returns:
        One :class:`Reconciliation` per instance, in input order.

    Raises:
        ValueError: If the three sequences have different lengths.
    """
    if not len(surface_categories) == len(polarities) == len(intensities):
        raise ValueError(
            f"length mismatch: {len(surface_categories)} categories, "
            f"{len(polarities)} polarities, {len(intensities)} intensities"
        )
    return [
        reconcile(category, polarity, intensity, cfg)
        for category, polarity, intensity in zip(
            surface_categories, polarities, intensities, strict=False
        )
    ]


__all__ = ["NO_RECONCILIATION", "Reconciliation", "reconcile", "reconcile_batch"]
